# Generated by Django 3.2.13 on 2022-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'comentarios',
            },
        ),
    ]
