# Generated by Django 3.2.13 on 2022-05-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Resuelto'), (False, 'Pendiente')], default=False),
        ),
    ]
